name: weather_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_getit: ^1.2.1
  get_it: ^7.6.4
  json_annotation: ^4.8.1
  retrofit: ">=4.0.0 <5.0.0"

dev_dependencies:
  build_runner: '>=2.3.0 <4.0.0'
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  retrofit_generator: '>=7.0.0 <8.0.0'

flutter:
  uses-material-design: true
