name: weather_app
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  equatable: ^2.0.5
  firebase_core: ^2.23.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_getit: ^1.2.1
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.6.0
  geocoding: ^2.1.1
  geolocator: ^10.1.0
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.5.0
  json_annotation: ^4.8.1
  retrofit: ">=4.0.0 <5.0.0"
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ">=2.3.0 <4.0.0"
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.2
  retrofit_generator: ">=7.0.0 <8.0.0"

flutter:
  uses-material-design: true

  assets:
    - assets/
